# Generated by Django 5.0.2 on 2024-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='star',
            field=models.CharField(max_length=255),
        ),
    ]
