# Generated by Django 5.0.2 on 2024-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='age',
            field=models.CharField(default='R-12', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='Frank Darabont', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.CharField(default='https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_QL75_UX140_CR0,1,140,207_.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='introduction',
            field=models.TextField(default='Over the course of several year'),
        ),
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.CharField(default='https://www.imdb.com/title/tt0111161/?ref_=chttp_i_1', max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='star',
            field=models.TextField(default='Tim Robbins, Morgan Freeman, Bob Gunton'),
        ),
    ]
