# Generated by Django 5.0.2 on 2024-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_movies_age_movies_director_movies_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='tag',
            field=models.CharField(default='Drama', max_length=255),
        ),
    ]
