# Generated by Django 5.0.2 on 2024-04-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_movies_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.rank'),
        ),
    ]
