# Generated by Django 5.0.4 on 2024-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_movies_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='introduction',
            field=models.TextField(),
        ),
    ]
