# Generated by Django 5.0.2 on 2024-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_forums_alter_movies_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
