# Generated by Django 5.0.2 on 2024-05-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_movies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default=1, max_length=255, null=True),
        ),
    ]
