# Generated by Django 5.0.2 on 2024-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
