# Generated by Django 5.0.2 on 2024-04-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_movies_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forums',
            new_name='Discussion',
        ),
        migrations.AlterModelTable(
            name='discussion',
            table='Discussion',
        ),
    ]
