# Generated by Django 5.0.2 on 2024-05-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_user_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
