# Generated by Django 5.0.2 on 2024-05-09 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_delete_articlecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('conent', models.TextField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.article')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.movies')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleComments',
                'managed': True,
                'unique_together': {('uid', 'time')},
            },
        ),
    ]
