# Generated by Django 5.0.2 on 2024-04-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_rename_forums_discussion_alter_discussion_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discussion',
            new_name='Forums',
        ),
        migrations.AlterModelTable(
            name='forums',
            table='Forums',
        ),
    ]
