# Generated by Django 5.0.4 on 2024-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0009_moviecomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecomments",
            name="content",
            field=models.TextField(default="test"),
        ),
    ]
