# Generated by Django 5.0.4 on 2024-05-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0010_alter_moviecomments_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecomments",
            name="mid",
            field=models.ForeignKey(
                default=300,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.movies",
            ),
        ),
    ]
