# Generated by Django 5.0.2 on 2024-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_forumsmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forums',
        ),
        migrations.DeleteModel(
            name='ForumsMessage',
        ),
    ]
