# Generated by Django 5.0.2 on 2024-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_articlecomments'),
        ('member', '0011_alter_moviecomments_mid'),
    ]

    operations = [
    ]
