# Generated by Django 5.0.2 on 2024-05-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_merge_20240520_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MPreference',
        ),
    ]
