# Generated by Django 5.0.2 on 2024-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_likemovies_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='mids',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
