# Generated by Django 5.0.2 on 2024-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Forums',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForumsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('m_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'ForumsMessage',
                'managed': True,
                'unique_together': {('f_id', 'm_id', 'time', 'content')},
            },
        ),
    ]
