# Generated by Django 5.0.2 on 2024-04-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forumsmessage_f_id_alter_forumsmessage_m_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumsmessage',
            old_name='content',
            new_name='message_content',
        ),
        migrations.AlterUniqueTogether(
            name='forumsmessage',
            unique_together={('f_id', 'm_id', 'time', 'message_content')},
        ),
    ]
