# Generated by Django 5.0.2 on 2024-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_content_forumsmessage_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
