# Generated by Django 5.0.2 on 2024-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forums_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsmessage',
            name='m_id',
            field=models.IntegerField(),
        ),
    ]
