# Generated by Django 5.0.2 on 2024-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrieTree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'TrieTree',
                'managed': True,
            },
        ),
    ]
