# Generated by Django 5.0.2 on 2024-05-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrieTree',
        ),
    ]
